### ISSUE TITLE
Fill out Tech Spec 

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/JuryInstructions#1]
### Task
We need to fill out the template tech spec a bit to help organize our efforts.  

### Acceptance Criteria
- [x] Intro paragraph written
- [ ] Overview written
- [ ] Single scenario written
- [ ] Non-goals written
- [ ] MVP written
